name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read Node.js version from .nvmrc
        id: node_version_from_nvmrc
        run: echo "node_version=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v2
        with:
            node-version: ${{ steps.node_version_from_nvmrc.outputs.node_version }}

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
