name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read Node.js version from .nvmrc
        id: node_version
        run: echo "node_version=$(cat .nvmrc) >> $GITHUB_ENV"

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v2
        with:
          node-version: $NODE_VERSION

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
